# Generated by Django 2.1.5 on 2019-03-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190310_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='pub_date',
        ),
    ]
